### ISSUE TITLE
Resolve the recursive  initialization of data

### ISSUE THREAD

**Issue by MatMT** [Javithor360/nexus-workshop#27]
For relational data between User and Activity

**Comment by MatMT** [comment]
![Image](https://github.com/user-attachments/assets/a1e514a4-3be9-4e36-a3d0-8faecd2460d8)

**Comment by Javithor360** [comment]
The problem has been handled and it's related on the way we manage external relations.

Those relations with other tables shouldn't be directly injected on the entity, they should be handled individually on the entity service.
